language: python

matrix:
  include:

    - os: linux
      python: 3.6
      sudo: required

    - os: linux
      python: 3.7
      sudo: required
      dist: xenial

    - os: osx
      python: 3.6
      language: generic

    - os: osx
      python: 3.7
      language: generic

#compiler:
#  - clang
#cache: pip

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - "pip install wheel pip setuptools cython --upgrade"
  - "pip install pytest"

script:
  - python setup.py build_ext --inplace
  - pytest -v -s

before_deploy: "echo 'ready'"

deploy:
  provider: pypi
  user: nooperpudd
  password:
    secure: nhH7QoPKNa6cbng456C4Stj4VjYy6cW6kmiSxvKgIMW3vzz3BDxQUJVnoVNwaKPy3zVIk8JR3UArnERU6avP6gKrsAsqkGRkBV7FclSd9fOTmOU2piiozp7rzRW5a71SsXX7XHR/cozBCxD5XogVDzuP+yRCGHWE1ABduh+Wgp2/wSIrP9iQu9TMgyBXcr1LYN6y7xKllHuyf/QgR/mrjw6MVDzZla0X0jYtD5Lew3Zyu/QLT11+tR4o0TRmozTNIjBrb2e9yOeNdTthVKOY0wtVYWEHQ382UqxQALvLcfvPb8u662UrUUpCNivvM2GXImXLTTS6ZMXy9/tLUjgtSbj8vdKeJ2CvN+l5fvMPZ7CvdC8hieyooZW791UYiiN/PYa9edAmqV075akAHOUOD75AVBu76hfXYm0yUHdwQq3Xr5pe97rvx1ihHNmIASBt3tVT24PS/nvnO+SXSpaBEk0eIMOiDPo2+7/MzmtAdlUfGwUcKFMWGT0+FkXX2yHZGRdE7O6EIZxMGen6DEwaSLnUWtw1jIabiB2q8Tc5eASJTjHaOqmc8hTz0bj/I0oJcPUeeABRgYsXFa26AwGqZTqp12vjHkAS1QLShSI2M6p4Zxr44UxayhVha8rDrIjf6zo0XiOKDeCDy/r7ceeqMpwFqOUQrcFuGFC3LMycw88=
  distributions: "sdist"
  on:
    tags: true
    python: '3.6.6'